import { Category } from "./merchant-menu-category.type";
import Office from "./office.type";

// export const categoryDummyData = [
//     { title: "Монгол", img: "placeholder.png" },
//     { title: "Ланч сэт", img: "placeholder.png" },
//     { title: "Солонгос", img: "placeholder.png" },
//     { title: "Япон", img: "placeholder.png" },
//     { title: "Хятад", img: "placeholder.png" },
//     { title: "Шөл", img: "placeholder.png" },
//     { title: "Хуурга", img: "placeholder.png" },
//     { title: "Ширхэгийн", img: "placeholder.png" },
//     { title: "Тахиа", img: "placeholder.png" },
//     { title: "Салад", img: "placeholder.png" },
//     { title: "Бургер", img: "placeholder.png" },
//     { title: "Бусад", img: "placeholder.png" },
// ];

export const dummyCategories: Category[] = [
    {
        id: "4054d817-6cd7-4d4f-b635-07454db060bb",
        name: "Монгол хоол",
        icon: "placeholder.png",
        children: [
            {
                id: "3ec73447-6c57-4bbf-b42d-85007a30844b",
                name: "Мантуун бууз",
                icon: "placeholder.png",
            },
            {
                id: "687799fc-d8a9-4c2e-873c-75d56383cd59",
                name: "Хуушуур",
                icon: "placeholder.png",
            },
            {
                id: "e24f0d92-56a3-4218-bf0e-051256cd014c",
                name: "Бууз",
                icon: "placeholder.png",
            },
        ],
    },
    {
        id: "416ec3db-6f6f-4362-afef-dd0f611a29ba",
        name: "Солонгос хоол",
        icon: "placeholder.png",
        children: [
            {
                id: "ac0d6d2d-885c-4a28-ba4c-839d8369f414",
                name: "Булгоги",
                icon: "placeholder.png",
            },
        ],
    },
    {
        id: "11bfa565-27a8-45ea-b473-67854a22b6a4",
        name: "Гоймон",
        icon: "placeholder.png",
        children: [
            {
                id: "d2461667-3efd-4905-a79e-65327d838093",
                name: "Бэлэн гоймон",
                icon: "placeholder.png",
            },
            {
                id: "126a31ef-bd83-4594-a6aa-99c223e54566",
                name: "Lapsha",
                icon: "placeholder.png",
            },
        ],
    },
    {
        id: "d0141b51-deb2-4867-a816-5b39f052bd60",
        name: "testsub",
        icon: "placeholder.png",
        children: [],
    },
];

export const dummyOffices: Office[] = [
    {
        id: "b7c85ea8-85a0-43c4-980d-a1a2d4ebcfa7",
        name: "Central",
        address: "UB",
        floor: 17,
        latitude: 333,
        longitude: 4441,
        photo: null,
        distance: 8364.8434087514,
        merchants: [],
    },
    {
        id: "6afebd9d-7b55-4ef8-b7d2-8b8582775110",
        name: "OFFICEE?",
        address: "UB",
        floor: 51,
        latitude: 0,
        longitude: 0,
        photo: null,
        distance: 11211.819802576769,
        merchants: [],
    },
];

export const recommendedDummyData = [
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
];

export const dummyProducts = [
    {
        img: "placeholder.png",
        title: "Гуляш",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
        outOfStock: true,
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
];

export const productFilters = ["Үнэлгээ", "Үнэ", "Хүргэлт", "Урамшуулал"];

export const dummyReviews = [
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
];
