export const categoryDummyData = [
    { title: "Монгол", img: "placeholder.png" },
    { title: "Ланч сэт", img: "placeholder.png" },
    { title: "Солонгос", img: "placeholder.png" },
    { title: "Япон", img: "placeholder.png" },
    { title: "Хятад", img: "placeholder.png" },
    { title: "Шөл", img: "placeholder.png" },
    { title: "Хуурга", img: "placeholder.png" },
    { title: "Ширхэгийн", img: "placeholder.png" },
    { title: "Тахиа", img: "placeholder.png" },
    { title: "Салад", img: "placeholder.png" },
    { title: "Бургер", img: "placeholder.png" },
    { title: "Бусад", img: "placeholder.png" },
];

export const recommendedDummyData = [
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        name: "Sushi gourment",
        oldPrice: "30000",
        newPrice: "29000",
        place: "Stockholm sushi",
        avgReview: "98",
    },
];

export const dummyProducts = [
    {
        img: "placeholder.png",
        title: "Гуляш",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
        outOfStock: true,
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
    {
        img: "placeholder.png",
        title: "Гөлөг",
        place: "Мандах",
        oldPrice: "7000",
        price: "6000",
        recipe: "Тахиан мах, сармис, сонгино, лууван, төмс, давс, перец, будаа",
        portions: ["Бүтэн", "Хагас"],
        spices: ["25", "50", "75"],
        avgReview: "98",
    },
];

export const productFilters = ["Үнэлгээ", "Үнэ", "Хүргэлт", "Урамшуулал"];

export const dummyReviews = [
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
    {
        name: "Одбат",
        image: "placeholder.png",
        comment: "Sda goy shaajinshde hamaa",
        date: "7 хоногийн өмнө",
    },
];
